#include <iostream>

using namespace std;

int main()
{
    int i = 1;

    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizzbuzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizzbuzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizzbuzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizzbuzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizzbuzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizzbuzz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << "buzz" << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << i << endl; ++i;
    cout << i << endl; ++i;
    cout << "fizz" << endl; ++i;
    cout << "buzz" << endl; ++i;

    return 0;
}
